### ISSUE TITLE
Bird movement isn't* tied to resolution

### ISSUE THREAD

**Issue by Tombez** [TheZeus121/java-javascript#1]
On Windows 7, 64 bit, making the game window larger makes the bird move "slowly" relative to the new resolution. Similarly, making the window smaller makes the bird move more relative to the resolution.

Theoretically, players could abuse this by making the window small when they want to move quickly, and as they go through a pipe, making the window larger would move it easier to avoid the hit-boxes.

More realistically though, it's un-playable at fullscreen, which is the issue.

**Comment by TheZeus121** [comment]
Fixed, was caused by vertical speed not being implemented correctly with a delta.
